// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.challenge.solution2.proto.lwwelementset

object LwwelementsetProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.any.AnyProto,
    com.google.protobuf.timestamp.TimestampProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.challenge.solution2.proto.lwwelementset.LWWElementSet,
      com.challenge.solution2.proto.lwwelementset.TimestampGSet
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChNsd3dlbGVtZW50c2V0LnByb3RvEh1jb20uY2hhbGxlbmdlLnNvbHV0aW9uMi5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2Fue
  S5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byK+AQoNTFdXRWxlbWVudFNldBJRCgZhZGRTZXQYASABKAsyL
  C5jb20uY2hhbGxlbmdlLnNvbHV0aW9uMi5wcm90by5UaW1lc3RhbXBHU2V0QgviPwgSBmFkZFNldFIGYWRkU2V0EloKCXJlbW92Z
  VNldBgCIAEoCzIsLmNvbS5jaGFsbGVuZ2Uuc29sdXRpb24yLnByb3RvLlRpbWVzdGFtcEdTZXRCDuI/CxIJcmVtb3ZlU2V0UglyZ
  W1vdmVTZXQi/QEKDVRpbWVzdGFtcEdTZXQSWgoHZW50cmllcxgBIAMoCzIyLmNvbS5jaGFsbGVuZ2Uuc29sdXRpb24yLnByb3RvL
  lRpbWVzdGFtcEdTZXQuRW50cnlCDOI/CRIHZW50cmllc1IHZW50cmllcxqPAQoFRW50cnkSPAoHZWxlbWVudBgBIAEoCzIULmdvb
  2dsZS5wcm90b2J1Zi5BbnlCDOI/CRIHZWxlbWVudFIHZWxlbWVudBJICgl0aW1lc3RhbXAYAiABKAsyGi5nb29nbGUucHJvdG9id
  WYuVGltZXN0YW1wQg7iPwsSCXRpbWVzdGFtcFIJdGltZXN0YW1wYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.any.AnyProto.javaDescriptor,
      com.google.protobuf.timestamp.TimestampProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}